# Generated by Django 5.2 on 2026-04-22 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Embarcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_embarcation', models.CharField(choices=[('pedalo', 'Pédaleau'), ('kayak', 'Kayak'), ('canoe', 'Canoë'), ('barque', 'Barque'), ('sup', 'Stand Up Paddle'), ('autre', 'Autre')], default='pedalo', max_length=20)),
                ('couleur', models.CharField(default='#3273dc', help_text='Couleur hex ex: #3273dc', max_length=7)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Embarcation',
                'verbose_name_plural': 'Embarcations',
                'ordering': ['ponton', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Ponton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ponton',
                'verbose_name_plural': 'Pontons',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embarcation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='pontons.embarcation')),
                ('gestionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['heure_debut'],
            },
        ),
        migrations.AddField(
            model_name='embarcation',
            name='ponton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarcations', to='pontons.ponton'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire'), ('visiteur', 'Visiteur')], default='visiteur', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
