# Generated by Django 5.2 on 2026-05-22 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['heure_debut'], name='pontons_loc_heure_d_98dd20_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['embarcation', 'heure_debut'], name='pontons_loc_embarca_eb4ba4_idx'),
        ),
    ]
