# Generated by Django 5.2 on 2026-05-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontons', '0003_location_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='Créée manuellement via admin (heure_fin fixe)'),
        ),
    ]
