# Generated by Django 5.2 on 2026-07-02 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontons', '0005_location_returned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarcation',
            name='couleur',
            field=models.CharField(default='#3273dc', help_text='Couleur hex ex: #3273dc', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Couleur hex invalide (format #RRGGBB).')]),
        ),
    ]
